apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jetstream-client
  namespace: isfiligoi
  labels: 
    k8s-app: jetstream-client
spec:
  template:
    metadata: 
      labels:
        k8s-app: jetstream-client
    spec:
      containers:
      - name: openstack-client
        image: sfiligoi/openstack-client:latest
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        resources:
           limits:
             memory: 4Gi
             cpu: 2
           requests:
             memory: 0.25Gi
             cpu: 0.25
        volumeMounts:
        - name: userconfig
          mountPath: /root/userconfig
          readOnly: true
      volumes:
      - name: userconfig
        configMap:
          name: jetstream-client

